### ISSUE TITLE
experimental branch errors out on backgroundImage

### ISSUE THREAD

**Issue by heatherdouglass** [web-animations/web-animations-js-legacy#590]
Hello,
If I create an animation that animates backgroundImage and then try to use the experimental `effectValueAtLocalTime` API I get an error, `TypeError: Cannot read property 'toCssValue' of undefined` at line 1821.  If I simply play the animation though then it does work.  Can the API be fixed for backgroundImage?  Thanks.
~Heather~

**Comment by shans** [comment]
Fix coming in #591

**Comment by shans** [comment]
Fixed in experimental and experimental-rebase

**Comment by heatherdouglass** [comment]
Hello,
Thanks for the quick turn around, but with the new code I am still seeing the same error, 'Uncaught TypeError: Cannot call method 'toCssValue' of undefined' at line 1821.
Thanks,
~Heather~

**Comment by shans** [comment]
Hi Heather,

Can you provide a test case?

Thanks,
    -Shane

**Comment by shans** [comment]
Sounds like this is fixed now.
